### ISSUE TITLE
Find the problem in the cost calculation at the beginning of the race, change slacks visualization on the plot for better readability

### ISSUE THREAD

**Issue by KarasevPavel** [Bauman-Racing-Team/MPCC#87]
issue number MPCC-45

**Comment by DoneZai** [comment]
Большое значение функции стоимости в начале связано с тем, что в Acados.m для входов используются веса rThrottle, rBrake и т.д., а не rdThrottle, rdBrake и т.д. Это приводит к тому, что входные данные меняются слишком быстро.

В последующем процессе в функции затрат существуют те же частичные максимумы. Это связано с большими значениями слэка, которые на данный момент кажутся разумными.

В plotdata был добавлен новый параметр constrAndSlacks для построения графика значений ограничений после воздействия слэка.
